### ISSUE TITLE
Implement local label resolution

### ISSUE THREAD

**Issue by moorts** [moorts/name_is_wip#19]
Labels in macros are 'local' labels, meaning their names are translated to unique names on macro reference, so there are no naming conflicts when the macro is used multiple times.

**Comment by moorts** [comment]
See pg. 46 of the 8080 Programmers Manual (pdf page 51)

**Comment by felixhir** [comment]
I would suggest to extend this issue to contain general locality regarding macros. Because not only labels have a local scope when declared within a macro, variables (defined with EQU/SET), do too. I will include this when working on the issue.
