### ISSUE TITLE
Map lines to memory bytes

### ISSUE THREAD

**Issue by felixhir** [moorts/name_is_wip#40]
The assembler should have a method to return the line corresponding to a certain byte so we can show the current "position of execution" in the frontend.

Should this be done by returning a large map like `fn get_line_mapping() -> HashMap<Range, i32>` or do we want a method like 
`fn get_line_of_byte(byte: i32) -> i32`?

**Comment by moorts** [comment]
I think it should return a map, however I think the type should be HashMap<u16, usize>, specific types aside, the point is that using Range as an indice seems impractical and its fine if sometimes two, or even three, subsequent indices map to the same value
